import { benefits, benefitsCheckedAt, benefitSources, benefitExclusions, benefitsKstDate, benefitWindow, benefitEligibility, selectBenefits } from './benefits.mjs';

const benefitEscape=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const benefitButton='seed-action-button seed-action-button--variant_neutralWeak seed-action-button--size_medium seed-action-button--layout_withText seed-action-button--size_medium-layout_withText';
const benefitLink=(url,label)=>`<a href="${benefitEscape(url)}" target="_blank" rel="noopener noreferrer">${benefitEscape(label)} ↗</a>`;
const benefitEvidence=ids=>ids.map(id=>benefitLink(benefitSources[id].url,benefitSources[id].title)).join('');
export function mountBenefits(root,state) {
 state.profile??={};state.filters??={};state.done??=[];
 function draw(){
  const p=state.profile,f=state.filters,today=benefitsKstDate(),rows=selectBenefits(p,f,today);
  const opened=new Set([...root.querySelectorAll('details[open]')].map(x=>x.dataset.detail));
  const select=(key,label,values,value)=>`<label class="rx-field"><span>${label}</span><select data-benefit-field="${key}" aria-label="${label}">${values.map(([v,t])=>`<option value="${benefitEscape(v)}" ${String(value??'')===String(v)?'selected':''}>${benefitEscape(t)}</option>`).join('')}</select></label>`;
  const hidden=benefits.map(b=>({b,w:benefitWindow(b,today),e:benefitEligibility(b,p)})).filter(x=>x.w.code!=='open'||x.e.code==='mismatch');
  const ageConflict=Number.isInteger(p.age)&&Number.isInteger(p.birthYear)&&![0,1].includes(Number(today.slice(0,4))-p.birthYear-p.age);
  root.innerHTML=`<div class="rb-hero"><span class="rb-eyebrow">학교 밖 청소년 · 기초생활수급자</span><h3>지금 신청할 혜택</h3><p>공식 자료 확인일 <strong>${benefitsCheckedAt} 한국시간</strong><br>신청 기간과 개인 자격을 따로 확인합니다.</p><div class="rb-meta"><span>공고·상시 신청 안내 ${benefits.filter(b=>benefitWindow(b,today).code==='open').length}개</span><span>현재 필터 후보 ${rows.length}개</span><span>신청 완료 표시 ${state.done.length}개</span></div></div>
  <div class="rb-notice"><strong>확인된 범위</strong><p>고교 자퇴·검정고시 응시·수급자라는 정보로 조사했습니다. 출생연도·급여 종류·거주 시군구가 없어 수혜 확정이나 전국 지역사업의 전수 확인은 할 수 없습니다. 등록된 서울 지역사업 외 지역 혜택은 별도 확인이 필요합니다.</p><p>공고상 접수 기간이어도 예산·정원·개인 이력에 따라 신청이 제한될 수 있습니다. 금액은 개인/가구, 월/연간, 현금/이용권을 구분했으며 서로 합산하지 않습니다.</p></div>
  ${today!==benefitsCheckedAt?`<p class="rb-alert" role="status">오늘은 ${today}입니다. 자료는 ${benefitsCheckedAt}에 확인한 기록이며 자동 갱신되지 않습니다. 신청 직전 공식 링크에서 변경·조기 마감을 재확인하세요.</p>`:''}
  <details class="rx-details" data-detail="profile"><summary>내 조건으로 좁히기 · 모르는 항목은 미확인으로</summary><div class="rb-profile">
  ${select('age','현재 만 나이',[['','미확인'],...Array.from({length:25},(_,i)=>[i,`${i}세`])],p.age)}
  ${select('birthYear','출생연도',[['','미확인'],...Array.from({length:25},(_,i)=>[2001+i,`${2001+i}년`])],p.birthYear)}
  ${select('region','주민등록상 거주 지역',[['','미확인'],['서울','서울'],['경기','경기'],['인천','인천'],['기타','그 밖의 시·도']],p.region)}
  ${select('gender','성별 조건',[['','미확인'],['female','여성'],['male','남성']],p.gender)}
  </div><fieldset class="rb-types"><legend>현재 받는 급여 · 모두 선택 / 선택하지 않으면 미확인</legend>${[['livelihood','생계'],['medical','의료'],['housing','주거'],['education','교육']].map(([v,t])=>`<label><input type="checkbox" data-benefit-type="${v}" ${(p.types??[]).includes(v)?'checked':''}> ${t}</label>`).join('')}</fieldset>
  ${ageConflict?'<p class="rb-alert">만 나이와 출생연도가 맞지 않습니다. 생일이 지났는지 확인하고 입력을 고쳐 주세요.</p>':''}
  <p class="jr-muted">입력은 이 화면의 메모리에만 유지됩니다. 주소·생년월일·증명서를 수집하지 않습니다. 초기화하면 조건과 완료 표시가 지워집니다.</p><button type="button" class="${benefitButton}" data-benefit-reset>조건·완료 표시 초기화</button></details>
  <form class="rb-filter"><label class="rx-field"><span>혜택 검색</span><input type="search" aria-label="혜택 검색" name="benefitQuery" value="${benefitEscape(f.query)}" placeholder="응시료, 전기, 건강…"></label>${select('category','분야',[['','전체 분야'],...new Set(benefits.map(b=>b.category))].map(v=>Array.isArray(v)?v:[v,v]),f.category)}<button class="${benefitButton}" type="submit">검색</button></form>
  <p class="jr-muted rb-result-count" role="status">현재 조건에서 ${rows.length}개 후보. ‘추천’은 마감·진학 관련성을 고려한 편집상 우선순위이며, 나머지 안내는 출처에 따른 사실입니다.</p>
  <div class="rb-grid">${rows.map(b=>`<article class="rb-card" data-benefit-id="${b.id}"><div class="rb-card-top"><span class="rb-kind">${benefitEscape(b.category)} · ${benefitEscape(b.kind)}</span>${state.done.includes(b.id)?'<span class="rb-done">완료 표시</span>':''}</div><h4>${benefitEscape(b.name)}</h4>${b.recommend?`<p class="rb-recommend">${benefitEscape(b.recommend)}</p>`:''}<p class="rb-amount">${benefitEscape(b.amount)}</p><p class="rb-period">${benefitEscape(b.period)}</p><span class="rb-condition">${benefitEscape(b.eligibility.label)}</span><p>${benefitEscape(b.target)}</p><details class="rb-detail" data-detail="${b.id}"><summary>신청 방법 · 제한 조건 · 공식 근거</summary><p><strong>신청 방법</strong><br>${benefitEscape(b.apply)}</p><ul>${b.conditions.map(c=>`<li>${benefitEscape(c)}</li>`).join('')}</ul><p>${benefitLink(b.url,'공식 신청·안내로 이동')}</p><div class="rb-sources">${benefitEvidence(b.sources)}</div><small>원문 확인: ${benefitsCheckedAt} · 실시간 잔여 예산 조회는 제공하지 않습니다.</small><label class="rx-check"><input type="checkbox" data-benefit-done="${b.id}" ${state.done.includes(b.id)?'checked':''}> 내가 신청 완료한 항목으로 표시</label></details></article>`).join('')||'<p class="rb-empty">현재 필터에 맞는 신청 후보가 없습니다. 미확인 조건·검색어를 확인해 주세요.</p>'}</div>
  <details class="rx-details" data-detail="excluded"><summary>현재 목록에서 제외·보류한 항목과 이유</summary>${hidden.map(({b,w,e})=>`<div class="rb-exclusion"><strong>${benefitEscape(b.name)}</strong><p>${benefitEscape(w.code!=='open'?w.label:e.mismatch.join(' · '))}</p><div class="rb-sources">${benefitEvidence(b.sources)}</div></div>`).join('')}${benefitExclusions.map(b=>`<div class="rb-exclusion"><strong>${benefitEscape(b.name)}</strong><p>${benefitEscape(b.reason)}</p><div class="rb-sources">${benefitEvidence(b.sources)}</div></div>`).join('')}</details>
  <details class="rx-details" data-detail="checklist"><summary>빠뜨린 지역 혜택 확인 · 상담 체크리스트</summary><p><strong>추천 준비 순서</strong>: 수급 급여 종류 확인 → 꿈드림센터 등록·상담 → 주민센터 요금감면·지역사업 확인.</p><ol><li>꿈드림센터에 “검정고시 이후 대학 진학 준비 중”이라고 알리고 현재 모집 중인 멘토링·진학상담·급식·교재·교통 지원을 확인하세요.</li><li>주민센터에 나이·급여 종류·시군구 기준으로 지역 장학금, 아동급식, 양곡, 상하수도·종량제봉투 감면의 현재 접수 여부를 문의하세요.</li><li>통신·전기·가스 고지서에서 이미 감면받는 항목인지 먼저 확인하세요. 신분증·수급자 증명·고객번호 등 필요한 자료는 신청 기관에 확인한 뒤 준비하세요.</li></ol><p>${benefitLink('https://www.bokjiro.go.kr/ssis-tbu/twatza/wmAplyMng/selectWmJoinProcGdnc.do','복지멤버십 안내')} · 맞춤형 급여 안내를 신청하는 기능이며 개별 지원의 자동 신청·지급은 아닙니다.</p><p>${benefitLink('https://www.1388.go.kr/occ/YTOSP_SC_OID_01','가까운 꿈드림센터 찾기')}</p><button type="button" class="${benefitButton}" data-benefit-copy>현재 후보 상담 목록 복사</button><p data-benefit-copy-status role="status"></p></details>`;
  root.querySelectorAll('details').forEach(d=>{if(opened.has(d.dataset.detail))d.open=true;});
  root.querySelectorAll('[data-benefit-field]').forEach(el=>el.addEventListener('change',()=>{const key=el.dataset.benefitField;if(key==='category')f.category=el.value;else p[key]=['age','birthYear'].includes(key)?(el.value===''?undefined:Number(el.value)):el.value;draw();root.querySelector(`[data-benefit-field="${key}"]`)?.focus();}));
  root.querySelectorAll('[data-benefit-type]').forEach(el=>el.addEventListener('change',()=>{p.types=[...root.querySelectorAll('[data-benefit-type]:checked')].map(x=>x.dataset.benefitType);draw();root.querySelector(`[data-benefit-type="${el.dataset.benefitType}"]`)?.focus();}));
  root.querySelector('.rb-filter').addEventListener('submit',e=>{e.preventDefault();f.query=new FormData(e.target).get('benefitQuery');draw();root.querySelector('[name="benefitQuery"]')?.focus();});
  root.querySelectorAll('[data-benefit-done]').forEach(el=>el.addEventListener('change',()=>{const id=el.dataset.benefitDone;state.done=el.checked?[...new Set([...state.done,id])]:state.done.filter(x=>x!==id);draw();root.querySelector(`[data-benefit-done="${id}"]`)?.focus();}));
  root.querySelector('[data-benefit-reset]').addEventListener('click',()=>{state.profile={};state.filters={};state.done=[];draw();});
  root.querySelector('[data-benefit-copy]').addEventListener('click',async()=>{const status=root.querySelector('[data-benefit-copy-status]');try{await navigator.clipboard.writeText(`혜택 상담 후보 · 공식자료 확인 ${benefitsCheckedAt}\n현재 자격·예산은 신청처 확인 필요\n\n`+rows.map(b=>`${state.done.includes(b.id)?'[완료 표시] ':''}${b.name}\n${b.period}\n${b.amount}\n${b.apply}\n${b.url}\n`).join('\n'));status.textContent='현재 후보 목록을 복사했습니다.';}catch{status.textContent='브라우저에서 복사를 허용하지 않았습니다. 화면의 신청 방법과 공식 링크를 확인해 주세요.';}});
 }
 draw();
}
